FROM reactnativecommunity/react-native-android

# Install custom tools, runtimes, etc.
# For example "bastet", a command-line tetris clone:
# RUN brew install bastet
#

RUN apt update && apt install fish -y
