FROM reactnativecommunity/react-native-android:5.2

# Install custom tools, runtimes, etc.
# For example "bastet", a command-line tetris clone:
# RUN brew install bastet
#

RUN apt update && apt install fish -y
RUN chmod 777 -R /opt/android